# Generated by Django 5.2.4 on 2025-07-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base', models.CharField(max_length=3)),
                ('currency', models.CharField(max_length=3)),
                ('value', models.FloatField()),
            ],
        ),
    ]
