# Generated by Django 5.2.4 on 2025-09-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='base',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BRL', 'BRL'), ('JPY', 'JPY')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
