# Generated by Django 5.2.4 on 2025-09-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_alter_rate_base_alter_rate_currency_alter_rate_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BRL', 'BRL'), ('JPY', 'JPY')], max_length=3),
        ),
    ]
