# Generated by Django 5.2.4 on 2025-11-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_alter_rate_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('BRL', 'BRL'), ('JPY', 'JPY')], max_length=3),
        ),
        migrations.AlterField(
            model_name='rate',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
